import {test,expect} from '@playwright/test';import fs from 'node:fs/promises';
const fixture=JSON.parse(await fs.readFile('fixtures/include-closure.json','utf8'));
test('JA EN controls, immutable existing entries, inert text, JSON download and responsive layout',async({page},info)=>{
 const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173/'))external.push(r.url());});
 await page.goto('/');await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#status')).toContainText('確認用の断片ができました');await expect(page.locator('#existing')).toHaveAttribute('readonly','');
 await page.locator('#language').click();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('#status')).toContainText('Fragment ready for manual review');
 const result=JSON.parse(await page.locator('#output').textContent());expect(result.ssh_connections.slice(0,2)).toEqual(fixture.existing.ssh_connections);expect(result.ssh_connections).toHaveLength(4);for(const c of result.ssh_connections.slice(2))expect(Object.keys(c).every(k=>['host','projects','nickname'].includes(k))).toBe(true);
 const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();await (await downloadPromise).saveAs(info.outputPath('ssh-connections.json'));
 const nickname=page.locator('[data-nickname="work-alt.invalid"]');await nickname.fill('<img src=x onerror="window.__xss=1">');await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#status')).toContainText('Changes have not been reviewed');await page.locator('#build').click();await expect(page.locator('#status')).toContainText('Fragment ready');await expect(page.locator('#output')).toContainText('<img src=x');expect(await page.locator('img').count()).toBe(0);expect(await page.evaluate(()=>window.__xss)).toBeUndefined();
 await page.locator('#reset').click();await expect(page.locator('#status')).toContainText('Fragment ready');const box=page.locator('[data-alias="build-box.invalid"]');await box.focus();await page.keyboard.press('Space');await expect(box).not.toBeChecked();await expect(page.locator('#download')).toBeDisabled();await page.locator('#build').click();await expect(page.locator('#status')).toContainText('1 appended');await box.focus();await page.keyboard.press('Space');await page.locator('#build').click();await expect(page.locator('#status')).toContainText('2 appended');
 await page.locator('#edit-workspace').click();await page.locator('#manifest').fill(JSON.stringify({...fixture,files:fixture.files.filter(f=>f.path!=='shared/build.conf')}));await expect(page.locator('#build')).toBeDisabled();await page.locator('#apply-input').click();await expect(page.locator('#error')).toContainText('missing Include');await expect(page.locator('#download')).toBeDisabled();await page.locator('#discard-input').click();await page.locator('#build').click();await expect(page.locator('#status')).toContainText('Fragment ready');
 const dup=structuredClone(fixture);dup.existing.ssh_connections.push(structuredClone(dup.existing.ssh_connections[1]));await page.locator('#manifest').fill(JSON.stringify(dup));await page.locator('#apply-input').click();await expect(page.locator('#error')).toContainText('Ambiguous existing');
 await page.locator('#reset').click();await expect(page.locator('#status')).toContainText('Fragment ready');await page.screenshot({path:info.outputPath('desktop-en.png'),fullPage:true});await page.locator('#language').click();await expect(page.locator('html')).toHaveAttribute('lang','ja');await page.screenshot({path:info.outputPath('desktop-ja.png'),fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('mobile-ja.png'),fullPage:true});await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('enlarged-text-ja.png'),fullPage:true});
 expect(errors).toEqual([]);expect(external).toEqual([]);await page.reload();await expect(page.locator('#status')).toContainText('確認用の断片ができました');
});
test('private-key markers rejected without echo, delayed imports superseded, oversized input blocked',async({page})=>{
 await page.addInitScript(()=>{const native=File.prototype.text;File.prototype.text=function(){const file=this;if(file.name!=='slow.json')return native.call(file);return new Promise(resolve=>setTimeout(async()=>{resolve(await native.call(file));window.__slowFinished=true;},350));};});
 await page.goto('/');await expect(page.locator('#download')).toBeEnabled();await page.locator('#language').click();
 const secret=structuredClone(fixture);secret.existing.ssh_connections[0].extra='-----BEGIN OPENSSH PRIVATE KEY-----';await page.locator('#file-input').setInputFiles({name:'rejected.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(secret))});await expect(page.locator('#error')).toContainText('Private-key markers');await expect(page.locator('#manifest')).toHaveValue('');expect(await page.locator('#output').textContent()).not.toContain('BEGIN OPENSSH');expect(await page.locator('#existing').inputValue()).not.toContain('BEGIN OPENSSH');await expect(page.locator('#download')).toBeDisabled();
 await page.locator('#reset').click();await expect(page.locator('#download')).toBeEnabled();const other=structuredClone(fixture);other.files[0].content+='Host late-import.invalid\n';other.selections=[];await page.locator('#file-input').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(other))});await page.locator('#reset').click();await page.waitForFunction(()=>window.__slowFinished);await expect(page.locator('[data-alias="late-import.invalid"]')).toHaveCount(0);await expect(page.locator('#download')).toBeEnabled();
 await page.locator('#edit-workspace').click();await page.locator('#manifest').fill('{"unapplied":true}');await expect(page.locator('#build')).toBeDisabled();
 await page.locator('#file-input').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(524289,32)});await expect(page.locator('#error')).toContainText('512 KiB');await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#build')).toBeDisabled();await expect(page.locator('#manifest')).toHaveValue('{"unapplied":true}');await page.locator('#reset').click();await expect(page.locator('#download')).toBeEnabled();
});
test('malformed ignored kept-selection fields cannot corrupt installed UI state',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#download')).toBeEnabled();const input=structuredClone(fixture);input.selections[0].projects='bad';input.selections[0].nickname=42;input.root='imported.conf';input.files[0].path='imported.conf';await page.locator('#file-input').setInputFiles({name:'kept-fields.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(input))});await expect(page.locator('.source-file.root')).toHaveText('imported.conf');await expect(page.locator('#build')).toBeEnabled();await page.locator('#build').click();await expect(page.locator('#download')).toBeEnabled();const result=JSON.parse(await page.locator('#output').textContent());expect(result.ssh_connections.slice(0,2)).toEqual(fixture.existing.ssh_connections);expect(errors).toEqual([]);});
test('worker startup failure never presents a successful result',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>window.Worker=undefined);await page.goto('/');await expect(page.locator('#error')).toContainText('Worker');await expect(page.locator('#download')).toBeDisabled();expect(errors).toEqual([]);});
